version: "2"
plugins:
  brakeman:
    enabled: true
  erblint:
    enabled: true
    config_file: .erb-lint.yml
  eslint:
    enabled: true
    channel: "eslint-4"
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-59
  scss-lint:
    enabled: true
