# https://github.com/eslint/eslint
eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore

# https://github.com/bbatsov/rubocop
rubocop:
  enabled: true
  config_file: .rubocop.yml

# https://github.com/sasstools/sass-lint
sass-lint:
  enabled: true
  config_file: .sass-lint.yml
