---
exclude_paths:
  - db/migrate
  - spec/dummy

detectors:
  BooleanParameter:
    enabled: false
  IrresponsibleModule:
    enabled: false
  UnusedPrivateMethod:
    enabled: true
  UtilityFunction:
    public_methods_only: true

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/inputs":
    InstanceVariableAssumption:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/policies":
    InstanceVariableAssumption:
      enabled: false
  "app/uploaders":
    UtilityFunction:
      enabled: false
