Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - '**/*.rake'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/routes.rb'
    - 'lib/archangel/testing_support/**/*.rb'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
