inherit_from:
  - .rubocop_disabled.yml
  - .rubocop_enabled.yml
  - .rubocop_exclude.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'spec/dummy/**/*'
    - 'RESOURCES/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
