# https://github.com/brigade/scss-lint/blob/master/config/default.yml
scss_files:
  - 'app/assets/stylesheets/**/*.scss'

exclude:
  - '**/*.css'
  - 'vendor/assets/stylesheets/**'

linters:
  ImportantRule:
    enabled: false

  NestingDepth:
    enabled: true
    max_depth: 4

  PlaceholderInExtend:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 4
