# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "pg", "~> 1.1"
  gem "pry-byebug", "~> 3.7"
  gem "sqlite3", "~> 1.4.1"
end

group :test do
  # Shared, general purpose gems
  gem "capybara", "~> 3.28"
  gem "database_cleaner", "~> 1.7"
  gem "factory_bot_rails", "~> 5.0"
  gem "rspec-rails", "~> 3.8"
  gem "shoulda-matchers", "~> 4.1"
end
