# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "rubocop", "~> 0.67", require: false
end

group :development, :test do
  gem "pry-byebug", "~> 3.6"
  gem "sqlite3", "~> 1.3.6"
  gem "thor", "~> 0.20"
end

group :test do
  # Shared, general purpose gems
  gem "capybara", "~> 3.21"
  gem "database_cleaner", "~> 1.7"
  gem "factory_bot_rails", "~> 5.0"
  gem "rspec-rails", "~> 3.8"
  gem "shoulda-matchers", "~> 4.0"
end
