# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "rubocop", "~> 0.67", require: false
end

group :development, :test do
  gem "pry-byebug", "~> 3.6"
  gem "sqlite3", "~> 1.3.6"
  gem "thor", "~> 0.20"
end

group :test do
  gem "capybara", "~> 3.8"
  gem "database_cleaner", "~> 1.7"
  gem "factory_bot_rails", "~> 4.11"
  gem "poltergeist", "~> 1.18"
  gem "rspec-rails", "~> 3.8"
  gem "shoulda-callback-matchers", "~> 1.1"
  gem "shoulda-matchers", "~> 3.1"
end
